apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  # sink-jdbcsnowflake-{database}-{schema}-{tabela}-{batch/online}-{agrupamento}-{p/m/g}
  name: sink-jdbcsnowflake-lz-sql-ih-prd-demo_cdc_3-clientes-online-m-v1
  labels:
    strimzi.io/cluster: inthub-prd
spec:
  autoRestart:
    enabled: true
  class: br.com.datastreambrasil.v3.SnowflakeSinkConnector
  tasksMax: 1
  config:
    topics: "source_debeziumsqlserver_demo_cdc_3_dbo_grupo1_online_m.DEMO_CDC_3.DBO.CLIENTES"
    url: "jdbc:snowflake://seuaccount.snowflakecomputing.com?schema=CRMB001D&db=LZ_SQL_IH_PRD&warehouse=WH_IH_PROD&CLIENT_SESSION_KEEP_ALIVE=TRUE&tracing=WARNING"
    user: "${secrets:snowflake-creds:username}"
    password: "${secrets:snowflake-creds:password}"
    stage: "CLIENTES"
    table: "CLIENTES"
    schema: "DEMO_CDC_3"

    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: "http://schema-registry-ih.kafka-admin:8081"
    key.converter.schemas.enable: true
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://schema-registry-ih.kafka-admin:8081"
    value.converter.schemas.enable: true
