apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  # source-debeziumsqlserver-{database}-{schema}-{grupo}-{online/batch}-{p/m/g}
  name: source-debeziumsqlserver-demo_cdc_2-dbo-grupo1-online-m
  labels:
    strimzi.io/cluster: inthub-prd
spec:
  autoRestart:
    enabled: true
  class: io.debezium.connector.sqlserver.SqlServerConnector
  tasksMax: 1
  config:
    database.hostname: "192.168.88.252"
    database.port: "1433"
    database.user: "${secrets:sqlserver-origem-demo_cdc_2:user}"
    database.password: "${secrets:sqlserver-origem-demo_cdc_2:password}"
    database.names: "DEMO_CDC_2"
    database.encrypt: false

    topic.prefix: "source_debeziumsqlserver_demo_cdc_2_dbo_grupo1_online_m"
    table.include.list: "dbo.Clientes"

    decimal.handling.mode: "string"
    tombstones.on.delete: false

    schema.history.internal.kafka.bootstrap.servers: kafka01:9092,kafka02:9092,kafka03:9092
    schema.history.internal.kafka.topic: "sh_source_debeziumsqlserver_demo_cdc_2_dbo_grupo1_online_m"

    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: "false"
    value.converter.schemas.enable: "true"

    data.query.mode: direct
    snapshot.locking.mode: none
    snapshot.isolation.mode: read_committed
    snapshot.max.threads: 5
